//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public enum GameState
{
	EMPTY,
	RUNNING,
	PAUSE,
	GAME_OVER,
	QUIT,
};

public static class GameBlackboard
{
	static public GameState	m_gameState = GameState.EMPTY;
	static public int		m_curScore = 0;
	static public int		m_highScore = 0;
	static GameObject		m_prefPopupQuit = null;
	static GameObject		m_popupQuit = null;

	static public void init()
	{

		m_prefPopupQuit = Resources.Load<GameObject>("Pref/PopupQuit");
		m_popupQuit = MonoBehaviour.Instantiate (m_prefPopupQuit, m_prefPopupQuit.transform.position, Quaternion.Euler (0, 0, 0)) as GameObject;
		m_popupQuit.SetActive(false);

	}

	static public void popupQuit()
	{
		m_gameState = GameState.QUIT;
		m_popupQuit.SetActive(true);
	}


	static public void		updateScore(int score)
	{
		if (m_highScore < score)
		{
			m_highScore = score;
		}

		m_curScore = score;
	}
}


